tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "node"

cask "anaconda"
cask "anki"
cask "arc"
cask "chatgpt"
cask "cloudflare-warp"
cask "docker-desktop"
cask "google-chrome"
cask "iterm2"
cask "logitech-options"
cask "microsoft-auto-update"
cask "monitorcontrol"
cask "obsidian"
cask "telegram"
cask "trunk-io"
cask "visual-studio-code"
cask "whatsapp"
cask "wireshark-chmodbpf"
cask "zoom"
