tap "aws/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"

#CLI
brew "readline"
brew "sqlite"
brew "xz"
brew "node"
brew "alexjs"
brew "anime-downloader"
brew "bat"
brew "broot"
brew "cask"
brew "choose"
brew "curlie"
brew "delta"
brew "docker"
brew "exa"
brew "fasd"
brew "fd"
brew "fortune"
brew "gh"
brew "git"
brew "gping"
brew "htop"
brew "httpie"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "mongocli"
brew "mysql"
brew "nnn"
brew "openssl@3"
brew "periscope"
brew "perl"
brew "php"
brew "postgresql"
brew "procs"
brew "pyenv"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "wget"
brew "wifi-password"
brew "wireshark"
brew "xh"
brew "xsv"
brew "z"
brew "zlib"

# Cloud Computing
brew "aws/tap/aws-sam-cli"
brew "hashicorp/tap/terraform"

#GUI
cask "alfred"
cask "flux"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "macdown"
cask "netnewswire"
cask "notion"
cask "numi"
cask "obsidian"
cask "rectangle"
cask "spotify"
cask "telegram"
cask "thinkorswim"
cask "vanilla"
cask "xbar"
cask "youtube-to-mp3"
cask "zoom"
mas "AdBlock Pro", id: 1018301773
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
