tap "aws/tap"
tap "charmbracelet/tap"
tap "cue-lang/tap"
tap "hashicorp/tap"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "stripe/stripe-cli"
tap "teamookla/speedtest"
brew "node"
brew "readline"
brew "xz"
brew "python@3.9"
brew "alexjs"
brew "anime-downloader"
brew "bat"
brew "bats-core"
brew "bazelisk"
brew "pkg-config"
brew "broot"
brew "cask"
brew "terraform"
brew "cdktf"
brew "choose"
brew "curlie"
brew "delta"
brew "deno"
brew "docker"
brew "duf"
brew "dust"
brew "fasd"
brew "fd"
brew "fortune"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gh"
brew "git"
brew "git-crypt"
brew "glow"
brew "go"
brew "go-jsonnet"
brew "gping"
brew "graphviz"
brew "hadolint"
brew "hadoop"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "iproute2mac"
brew "jenkins"
brew "jenkins-lts"
brew "jq"
brew "jupyterlab"
brew "kubernetes-cli"
brew "links"
brew "llvm"
brew "lsd"
brew "mas"
brew "maven"
brew "minikube"
brew "mongocli"
brew "nnn"
brew "openssl@3"
brew "periscope"
brew "perl"
brew "php"
brew "postgresql"
brew "procs"
brew "pyenv"
brew "rabbitmq"
brew "redis"
brew "ripgrep"
brew "sd"
brew "the_silver_searcher"
brew "tldr"
brew "tree"
brew "wget"
brew "wifi-password"
brew "wireshark"
brew "xh"
brew "xsv"
brew "z"
brew "zlib"
brew "zoxide"
brew "aws/tap/aws-sam-cli"
brew "aws/tap/lightsailctl"
brew "cue-lang/tap/cue"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/terraform"
brew "stripe/stripe-cli/stripe"
brew "teamookla/speedtest/speedtest"
cask "anki"
cask "aws-vault"
cask "flutter"
cask "flux"
cask "google-chrome"
cask "inso"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "mamp"
cask "mongodb-compass"
cask "netnewswire"
cask "notion"
cask "numi"
cask "obsidian"
cask "onedrive"
cask "postman"
cask "soapui"
cask "spotify"
cask "telegram"
cask "thinkorswim"
cask "visual-studio-code"
cask "youtube-to-mp3"
cask "zoom"
mas "AdBlock Pro", id: 1018301773
mas "Asphalt 9", id: 1491129197
mas "Developer", id: 640199958
mas "feedly", id: 865500966
mas "iMovie", id: 408981434
mas "Instapaper", id: 288545208
mas "Instapaper Save", id: 1481302432
mas "Notability", id: 360593530
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "WeChat", id: 836500024
mas "WhatsApp", id: 1147396723
mas "Wireless@SGx", id: 1449928544
mas "Xcode", id: 497799835
mas "YoudaoDict", id: 491854842
