---
- name: Setup new MacBook
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: homebrew
    - role: dotfiles
    - role: osx-settings
    - role: cli-tools
