---

- name: Check if dotfile destinations already exist
  ansible.builtin.stat:
    path: "~/{{ item }}"
  register: dotfiles_stat
  loop: "{{ dotfiles_files }}"

- name: Create symlinks for dotfiles
  ansible.builtin.file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item.item }}"
    dest: "~/{{ item.item }}"
    state: link
    follow: false
    force: yes
  loop: "{{ dotfiles_stat.results }}"
  when: not item.stat.exists
