- name: Ensure Homebrew is installed
  homebrew:
    state: present

- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"


- name: Clone the dotfiles repository
  git:
    repo: 'https://github.com/BradleyYeo/dotfiles.git'
    dest: '~/dotfiles'
    update: yes

- name: Read the Brewfile
  slurp:
    src: '~/dotfiles/Brewfile'
  register: brewfile_content

- name: Create a temporary Brewfile
  copy:
    content: "{{ brewfile_content.content | b64decode }}"
    dest: '/tmp/Brewfile'

- name: Install packages from Brewfile
  shell: brew bundle --file=/tmp/Brewfile