---
- name: Ensure Documents directory exists
  ansible.builtin.file:
    path: ~/Documents
    state: directory

- name: Clone private repositories using GitHub CLI
  ansible.builtin.command:
    cmd: "gh repo clone {{ item.repo }} {{ item.dest }}"
    creates: "{{ item.dest }}"
  loop: "{{ github_repos_to_clone }}"

- name: Pull latest changes for existing repositories
  ansible.builtin.command:
    cmd: "git pull"
    chdir: "{{ item.dest }}"
  loop: "{{ github_repos_to_clone }}"
  register: git_pull_result
  changed_when: "'Already up to date.' not in git_pull_result.stdout"
  ignore_errors: true

- name: Install all project dependencies
  ansible.builtin.pip:
    requirements: "{{ playbook_dir }}/requirements.txt"

- name: Load encrypted secrets
  ansible.builtin.include_vars:
    file: vars/secrets.yml

- name: Create wallpapers directory
  ansible.builtin.file:
    path: "~/Documents/Wallpapers"
    state: directory
    mode: "0755"

- name: List all objects in the wallpapers bucket
  amazon.aws.s3_object_info:
    bucket_name: wallpapers
    access_key: "{{ vault_r2_access_key }}"
    secret_key: "{{ vault_r2_secret_key }}"
    endpoint_url: https://{{ vault_account_id }}.r2.cloudflarestorage.com
    region: "auto"
  register: r2_files

- name: Sync wallpapers from Object Storage
  amazon.aws.s3_object:
    bucket: wallpapers
    object: "{{ item }}"
    dest: "~/Documents/Wallpapers/{{ item }}"
    mode: get
    access_key: "{{ vault_r2_access_key }}"
    secret_key: "{{ vault_r2_secret_key }}"
    endpoint_url: https://{{ vault_account_id }}.r2.cloudflarestorage.com
    region: "auto"
  loop: "{{ r2_files.s3_keys }}"
  loop_control:
    label: "{{ item }}"